"use client";
import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import lock from "@/assets/lock2.png";
import Image from "next/image";
import winning from "@/assets/winning.png";
import { Tooltip } from "@mui/material";
import { CircularProgress, Box, Typography } from "@mui/material";
import { useSearchParams, useRouter } from "next/navigation";
import LoadingButton from "@mui/lab/LoadingButton";

export const metadata: Metadata = {
  title: "Claim Evaluation Report",
  description: "Generated by create next app",
};

export default function EvaluationReport({
  role,
  data,
}: {
  role: any;
  data: any;
}) {
  const params = useSearchParams();
  const router = useRouter();
  const id = params?.get("id");
  const [load, setLoad] = useState(false);
  return (
    <div className="evaluation-rrt">
      <div className="row">
        <div className="col-12 col-md-10">
          {data?.questions?.map((itm: any, i: any) => {
            return (
              <div key={i} className="flex flex-col graph_dev mt-3">
                <h3 className="f-16 dark semi-bold mt-4 pb-1">
                  {itm?.question}{" "}
                </h3>

                <div className="bglght border rounded-radius client-address p-3">
                  <div className="row">
                    <div className="col-12 col-md-8 col-lg-9">
                      <Tooltip
                        key={i}
                        placement="top"
                        title={`${
                          role == "client" &&
                          itm?.isLock &&
                          data?.status !== "accept" &&
                          !data?.isPurchased
                            ? "You don't have subscription to view this."
                            : ""
                        }`}
                      >
                        <p className="f-15 mb-0">
                          {role == "client" &&
                          itm?.isLock &&
                          data?.status !== "accept" &&
                          !data?.isPurchased
                            ? itm?.answer?.substr(0, itm?.limit) + "..."
                            : itm?.answer}
                        </p>
                      </Tooltip>
                    </div>
                    <div className="col-12 col-md-4 col-lg-3">
                      <div className="success-rate-btns d-flex gap-2 align-items-center justify-content-end">
                        {itm?.isLock &&
                          !(
                            role === "client" &&
                            (data?.status === "accept" ||
                              (data?.status === "reject" && data?.isPurchased))
                          ) && (
                            <Image
                              src={lock}
                              className="down-link"
                              alt="lock"
                            />
                          )}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
      <div className="row">
        <div className="col-12 col-md-8">
          {role !== "client" && (
            <div className="row align-items-center write-percent mt-4">
              <div className="col-12 col-md-3">
                <p className="f-16 dark mb-0">Winning Percentage</p>
              </div>
              <div className="col-12 col-md-6">
                <input
                  className="form-control"
                  disabled
                  value={data?.winning_percentage}
                />
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Graphs */}
      <div className="row">
        <div className="col-12 col-md-9 mt-5">
          <div className="row">
            <div className="col-12 col-md-12 col-lg-8 col-xl-5 col-xxl-4">
              <div className="winning-percent ">
                {role == "client" &&
                data?.status !== "accept" &&
                !data?.isPurchased ? (
                  <div className=" mb-3">
                    <Image src={winning} alt="Winning" className="winning" />
                  </div>
                ) : (
                  <div
                    className="p-3 rounded mb-3 text-center"
                    style={{ backgroundColor: "#D6F4E5" }}
                  >
                    <h3 className="f-20">Wining Percentage</h3>

                    <Box
                      position="relative"
                      display="inline-flex"
                      justifyContent="center"
                      alignItems="center"
                    >
                      {/* Background Circle */}
                      <CircularProgress
                        variant="determinate"
                        value={100}
                        size={200}
                        thickness={6}
                        sx={{
                          color: "lightgrey",
                          position: "absolute",
                          zIndex: 1,
                        }}
                      />

                      <CircularProgress
                        color="success"
                        variant="determinate"
                        value={data?.winning_percentage}
                        size={200}
                        thickness={6}
                        sx={{
                          position: "relative",
                          zIndex: 2,
                        }}
                      />
                      <Box
                        position="absolute"
                        display="flex"
                        justifyContent="center"
                        alignItems="center"
                        width="100%"
                        height="100%"
                      >
                        <Typography
                          variant="caption"
                          component="div"
                          color="dark"
                          sx={{
                            fontSize: "22px",
                            fontWeight: "800",
                          }}
                        >
                          {data?.winning_percentage}
                          {"%"}
                        </Typography>
                      </Box>
                    </Box>
                  </div>
                )}

                <div
                  className="p-3 rounded mb-2"
                  style={{ backgroundColor: "#D6F4E5" }}
                >
                  <h3 className="f-18 mb-1">Description </h3>
                  <p className="mb-0 f-14 gray">{data?.description}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="prepare-btns d-flex gap-3 align-items-center mt-3">
        {data?.isFinancialReport && (
          <LoadingButton
            loading={load}
            variant="contained"
            type="submit"
            className="load-btn"
            size="large"
            onClick={() => {
              setLoad(true);
              router.push(`/${role}/financial-report?id=` + id);
            }}
          >
            View Financial Report
          </LoadingButton>
        )}

        {role === "expert" && !data?.isFinancialReport && (
          <LoadingButton
            loading={load}
            variant="contained"
            type="submit"
            className="load-btn"
            size="large"
            onClick={() => {
              setLoad(true);
              router.push(`/expert/create-financial-report?id=` + id);
            }}
          >
            Create Financial Report
          </LoadingButton>
        )}
      </div>
    </div>
  );
}
